### ISSUE TITLE
Harmony 17 Premium support ?

### ISSUE THREAD

**Issue by nyue** [diegogarciahuerta/tk-harmony#2]
Hi,

  The README mentioned Harmony 16 and above. I am testing with Harmony 17 and didn't see the shotgun menu. I am going to troubleshoot but are you able to confirm with tk-harmony is tested with Harmony 17 yet ?

Cheers

**Comment by diegogarciahuerta** [comment]
I'm curious what version of 17 you are using, it could be related to this pull request
https://github.com/diegogarciahuerta/tk-harmony/pull/1

It seems that Harmony only uses the major portion of the version for the scripts directory, (ie. you might be using version 17.0.2 and the scripts folder is still "1700-scripts") , so it might be copying the scripts to the wrong location. 

I will give it a try when I get a chance!

**Comment by nyue** [comment]
Version 17.0.1

![image](https://user-images.githubusercontent.com/486172/76239459-d876da80-61ee-11ea-897c-eae5f6455b88.png)

**Comment by nyue** [comment]
Note also that we are starting in "database" mode rather than standalone mode, if that makes a difference.

**Comment by nyue** [comment]
Seems like the toolkit overrides the windows argument we pass via shotgun, it always has the -debug option when I launch Harmony

2020-03-09 14:05:59,941 [   DEBUG] [PROXY] Launching executable 'C:\Program Files (x86)\Toon Boom Animation\Toon Boom Harmony 17 Premium\win64\bin\HarmonyPremium.exe' with args ' -debug "C:\Users\nyue\AppData\Roaming\Shotgun\bundle_cache\git\tk-harmony.git\v1.0.0\resources\templates\startup\template.xstage"'

**Comment by diegogarciahuerta** [comment]
Thanks @nyue . I've released [v1.0.1](https://github.com/diegogarciahuerta/tk-harmony/releases/tag/v1.0.1) which should address the engine not showing up the menu in versions newer than 17.0.0 , as the scripts were copied to the wrong location.  Let me know if that works for you, please.

In regards of launching it with the database mode, would you know how to run harmony from the command line in that mode ? Feel free to create a different issue for that.

Cheers,

- Diego

**Comment by nyue** [comment]
Thansk @diegogarciahuerta , I can confirm with v1.0.1 , the Shotgun menu is showing up in Harmony 17.0.1

**Comment by fjjdnfjj** [comment]
How to operate

**Comment by fjjdnfjj** [comment]
How to operate
